name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show project tree (top 3 levels)
        run: |
          ls -la
          find . -maxdepth 3 -type d -print
          echo "-------- files --------"
          find . -maxdepth 2 -name "build.gradle*" -o -name "settings.gradle" -o -name "gradlew" -print

      - name: Ensure Gradle wrapper is executable
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
          else
            echo "::error ::Gradle wrapper (gradlew) not found at repo root."
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: Build (assembleDebug)
        run: ./gradlew --no-daemon clean assembleDebug

      - name: List generated APKs/AABs
        run: |
          echo "---- outputs ----"
          ls -R */build/outputs || true

      - name: Upload all APKs
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: |
            **/build/outputs/apk/**/*.apk
            **/build/outputs/bundle/**/*.aab
          if-no-files-found: warn
